# Site settings
title: Lost Egg

# These are overridden by Github. They're here for local rendering
github:
  repository_url: https://github.com/lost-egg/lost-egg.github.io
  issues_url: https://github.com/lost-egg/lost-egg.github.io/issues

exclude:
  - CNAME
  - CONTRIBUTING.md
  - Gemfile
  - Gemfile.lock
  - README.md

permalink: pretty

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: charms
    values:
      layout: charm

collections:
  charms:
    permalink: /:collection/:title/
    output: true
